# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Excessively Adequate
email: hi@noahdoersing.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog on software development and other things that interest me.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://excessivelyadequate.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /posts/:title.html

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-minifier
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md

jekyll-minifier:
  exclude:
    - 'feed.json'
    - 'feed.xml'
    - 'assets/katex/*'
    - 'assets/fonts/*'
    - 'static/*'
